version: 1.0.{build}
configuration: Release
platform: Any CPU
nuget:
  disable_publish_on_pr: true
build:
  project: ./src/fastipc.sln
  publish_nuget: true
  verbosity: normal
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#appveyor-ci'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false